name: Build and Push Image
on:
  push:
    paths:
      - '.github/workflows/push_container.yaml'
      - 'Dockerfile'

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    name: Build and push image
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    # - name: Build Image
    #   id: build-image
    #   uses: redhat-actions/buildah-build@v2
    #   with:
    #     image: datascience
    #     tags: latest ${{ github.sha }}
    #     containerfiles: |
    #       ./Dockerfile
    # get a hello world image to test push
    - name: Run hello world
      id: run-hello-world
      uses: redhat-actions/buildah-run@v2
      with:
        image: hello-world
        tags: latest ${{ github.sha }}
        base-image: docker.io/library/hello-world:latest

    # Podman Login action (https://github.com/redhat-actions/podman-login) also be used to log in,
    # in which case 'username' and 'password' can be omitted.
    - name: Push To quay.io
      id: push-to-quay
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.run-hello-world.outputs.image }}
        tags: ${{ steps.run-hello-world.outputs.tags }}
        registry: quay.io/babaolanqiu
        username: babaolanqiu
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Print image url
      run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"